### ISSUE TITLE
Add this plugin throw a TypeError

### ISSUE THREAD

**Issue by chentsulin** [4Catalyzer/babel-plugin-dev-expression#2]
Try to add this plugin into .babelrc but throw a TypeError, and everything works normally after removed it.

```
/Users/chentsulin/Projects/electron-react-boilerplate/node_modules/babel-core/lib/transformation/file/index.js:591
      throw err;
      ^

TypeError: /Users/chentsulin/Projects/electron-react-boilerplate/webpack.config.production.js: Property key of ObjectProperty expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "BinaryExpression"
    at validate (/Users/chentsulin/Projects/electron-react-boilerplate/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/Users/chentsulin/Projects/electron-react-boilerplate/node_modules/babel-types/lib/definitions/core.js:507:63)
    at Object.validate (/Users/chentsulin/Projects/electron-react-boilerplate/node_modules/babel-types/lib/index.js:541:9)
    at NodePath._replaceWith (/Users/chentsulin/Projects/electron-react-boilerplate/node_modules/babel-traverse/lib/path/replacement.js:214:7)
```

More detail Info:
PR: https://github.com/chentsulin/electron-react-boilerplate/pull/238/files
Travis Build: https://travis-ci.org/chentsulin/electron-react-boilerplate/jobs/135365374

**Comment by taion** [comment]
It's because of https://github.com/chentsulin/electron-react-boilerplate/blob/6698a036ba529fdbd72298e1f378db1e127d43d8/webpack.config.production.js#L46. This plugin replaces `__DEV__` with the `NODE_ENV` check.

**Comment by cooperka** [comment]
I'm getting a very similar error using React Native v0.43:

```
Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "BinaryExpression"
```

@taion I've removed all references to `__DEV__` and `NODE_ENV` in my own project just in case. Any idea how this might be occurring? The stack trace isn't very helpful unfortunately since it doesn't say which file is actually causing the problem.

Full stack:

```console
error: bundling: TypeError: /Users/me/dev/apps/my-app/node_modules/react-native/packager/src/Resolver/polyfills/prelude_dev.js: Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "BinaryExpression"
    at validate (/Users/me/dev/apps/my-app/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/Users/me/dev/apps/my-app/node_modules/babel-types/lib/definitions/core.js:412:50)
    at Object.validate (/Users/me/dev/apps/my-app/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/Users/me/dev/apps/my-app/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (/Users/me/dev/apps/my-app/node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at PluginPass.enter (/Users/me/dev/apps/my-app/node_modules/babel-plugin-dev-expression/dev-expression.js:41:18)
    at newFn (/Users/me/dev/apps/my-app/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/me/dev/apps/my-app/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/me/dev/apps/my-app/node_modules/babel-traverse/lib/path/context.js:48:17)
TransformError: /Users/me/dev/apps/my-app/node_modules/react-native/packager/src/Resolver/polyfills/prelude_dev.js: /Users/me/dev/apps/my-app/node_modules/react-native/packager/src/Resolver/polyfills/prelude_dev.js: Property property of MemberExpression expected node to be of a type ["Identifier"] but instead got "BinaryExpression"
Bundling `index.ios.js`  100.0% (1991/1991), failed.
```

`.babelrc`:

```js
{
  "presets": [
    "react-native-stage-0"
  ],
  "plugins": [
    "dev-expression"
  ]
}
```
